#!/usr/bin/env node
/**
 * Build step for CALM (Common Architecture Language Model) rendering.
 *
 * The FINOS CALM CLI (`calm docify`) generates a full standalone Docusaurus
 * project. We only want the rendered architecture (a Mermaid diagram) embedded
 * in *our* site, so this script:
 *   1. runs `calm validate` then `calm docify` into a temp directory,
 *   2. extracts the generated Mermaid diagram from the docify output,
 *   3. writes it as an MDX partial into `src/calm/<name>.mdx`.
 *
 * The partial is then imported by pages via:
 *   import WebsiteArchitecture from '@site/src/calm/website.mdx';
 *   <WebsiteArchitecture />
 */
import {execFileSync} from 'node:child_process';
import {mkdtempSync, rmSync, mkdirSync, readFileSync, writeFileSync, readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, basename} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const calmDir = join(root, 'calm');
const outDir = join(root, 'src', 'calm');

// Discover every *.architecture.json in the calm/ directory.
let archFiles = [];
try {
  archFiles = readdirSync(calmDir).filter((f) => f.endsWith('.architecture.json'));
} catch {
  console.log('[calm] no calm/ directory found, skipping.');
  process.exit(0);
}

if (archFiles.length === 0) {
  console.log('[calm] no *.architecture.json files found, skipping.');
  process.exit(0);
}

mkdirSync(outDir, {recursive: true});

const calmBin = join(root, 'node_modules', '.bin', 'calm');

/** Extract the first ```mermaid ... ``` fenced block from markdown text. */
function extractMermaid(md) {
  const match = md.match(/```mermaid\n([\s\S]*?)```/);
  return match ? match[1].trimEnd() : null;
}

for (const file of archFiles) {
  const name = basename(file, '.architecture.json');
  const archPath = join(calmDir, file);
  const tmp = mkdtempSync(join(tmpdir(), `calm-${name}-`));

  try {
    // Validate first — fail the build early on a broken model.
    execFileSync(calmBin, ['validate', '-a', archPath], {stdio: 'inherit'});

    // Generate docs into a throwaway directory.
    execFileSync(calmBin, ['docify', '-a', archPath, '-o', tmp, '--clear-output-directory'], {
      stdio: 'inherit',
    });

    const indexMd = readFileSync(join(tmp, 'docs', 'index.md'), 'utf8');
    const mermaid = extractMermaid(indexMd);

    if (!mermaid) {
      throw new Error(`No mermaid diagram found in docify output for ${file}`);
    }

    const mdx = `{/* AUTO-GENERATED by scripts/build-calm.mjs from calm/${file}. Do not edit. */}

\`\`\`mermaid
${mermaid}
\`\`\`
`;
    const outFile = join(outDir, `${name}.mdx`);
    writeFileSync(outFile, mdx, 'utf8');
    console.log(`[calm] wrote src/calm/${name}.mdx`);
  } finally {
    rmSync(tmp, {recursive: true, force: true});
  }
}
